#### Which model is predicting the best?
For the subset of 27-75 year olds, Random Forest and Support Vector Machines were the most successful at predicting ~85% correct. The Elastic Net had the lowest correct prediction rate of ~59% but this was to be expected as this ML method is not made for 0/1 variable, it is made for continuous data, not discrete.
#### What is the trade-off between false positives vs false negatives?
True Positive: People WITH Health Insurance, predicted to HAVE health insurance
False Positive: People WITHOUT Health Insurance, predicted to HAVE health insurance
True Negative: People WITHOUT Health Insurance, predicted to NOT HAVE health insurance
False Negative: People WITH Health Insurance, predicted to NOT HAVE health insurance
Consequence of a False Positive: Someone has been predicted to have health insurance when in reality they do not have health insurance. If we let this person go to the doctor's they are going to receive a massive bill ~$1000+ just for a visit to the doctor's! This person may also act more reckless because they think they have health insurance to cover them if they get hurt, when in fact they would not if they had to go to the emergency room. This is called moral hazard.
Consequence of a False Negative: Someone has been predicted to not have health insurance but in reality does have health insurance. Since this person is covered in reality but they don't think they are, if they actually get hurt with a life-threatening injury, they will have to go to the emergency room even if they know they don't have health insurance. They will be pleasantly surprised to find out that they did have health insurance after they have recovered from their injury.
Conclusion: You want to avoid False Positives more than you want to avoid False Negatives because of the moral hazard as those people would not worry about getting hurt "thinking" that they do not bear the full cost of their medical bills if they do.
#### Which of the explanatory variables are consistently more or less useful?